#include <string>
#include <vector>
#include <iostream>
#include <bits/stdc++.h>

using namespace std;

// generated by GEMINI
std::vector<std::string> splitString(const std::string& stringToSplit, const std::vector<char>& delims) {
    std::vector<std::string> split;
    
    std::string delimString(delims.begin(), delims.end());
    std::string::size_type start = 0;

    while (start < stringToSplit.length()) {
        std::string::size_type end = stringToSplit.find_first_of(delimString, start);

        if (end == std::string::npos) {
            std::string remainingToken = stringToSplit.substr(start);
            if (!remainingToken.empty()) {
                split.push_back(remainingToken);
            }
            break;
        }

        std::string token = stringToSplit.substr(start, end - start);
        
        if (token.empty()) {
            start = end + 1;
            continue;
        }

        split.push_back(token);
        start = end + 1;
    }

    return split;
}