#include <string>
#include <vector>
#include <iostream>
#include <bits/stdc++.h>

#include "./headers/tokens.hpp"
using namespace std;

// generated by GEMINI
namespace Util {
  std::vector<std::string> splitString(const std::string& stringToSplit, const std::vector<char>& delims) {
      std::vector<std::string> split;
      if (stringToSplit.empty()) {
          return split;
      }
      
      std::string delimString(delims.begin(), delims.end());
      std::string::size_type start = 0;

      while (start < stringToSplit.length()) {
          std::string::size_type end = stringToSplit.find_first_of(delimString, start);

          if (end == std::string::npos) {
              std::string remainingToken = stringToSplit.substr(start);
              if (!remainingToken.empty()) {
                  split.push_back(remainingToken);
              }
              break;
          }

          std::string token = stringToSplit.substr(start, end - start);
          
          if (token.empty()) {
              start = end + 1;
              continue;
          }

          split.push_back(token);
          start = end + 1;
      }

      return split;
  }

  std::vector<std::string> tokenize(const std::string& stringToSplit) {
      std::vector<std::string> tokens;
      for (size_t i = 0; i < stringToSplit.length(); ) {
          if (std::isspace(stringToSplit[i])) {
              i++;
              continue;
          }
          
          size_t start = i;
          i++;
          
          if (i < stringToSplit.length() && stringToSplit[i] == '(') {
              int depth = 1;
              i++;
              while (i < stringToSplit.length() && depth > 0) {
                  if (stringToSplit[i] == '(') depth++;
                  else if (stringToSplit[i] == ')') depth--;
                  i++;
              }
          }
          tokens.push_back(stringToSplit.substr(start, i - start));
      }
      return tokens;
  }


  bool isNumeric(const std::string& text) {
    if (text.empty()) {
        return false;
    }

    float value;
    auto [ptr, ec] = std::from_chars(text.data(), text.data() + text.length(), value);

    if (ec != std::errc() || ptr != text.data() + text.length()) {
      return false;
    }

    return true;
  }
}
